ra:
  key: ra.key
  crt: ra.crt
  nmapxml: .
  host: 127.0.0.1
  port: 1323
  secret: secret
  sqlite: sqlite.db
  workers:
    queue: 25
    count: 5
    scanner_attempts: 3
    responser_attempts: 3
    tick: 5
rism:
  host: 127.0.0.1
  port: 3000
  protocol: http
  secret: 4b69a51caf56bce8086207c9e634833c
