ra:
  key: ra.key
  crt: ra.crt
  nmapxml: ./nmapxml
  host: 0.0.0.0
  port: 1323
  protocol: https
  secret: secret
  sqlite: ./db/sqlite.db
  mode: sudo
  workers:
    queue: 25
    count: 5
    attempts: 3
    tick: 5
    timeout: 12
  responser:
    attempts: 3
  planer:
    tick: 5
rism:
  host: 127.0.0.1
  port: 3000
  protocol: http
  secret: 011a54f3922298708bdf2677fcfb8829
  #secret: a4ead3eada915def5cfebd62c0b57ae0
